### ISSUE TITLE
passbook not install iOS8

### ISSUE THREAD

**Issue by michelmelo** [SimonWaldherr/passkit.php#6]
hello I am not able to install the ios8.

**Comment by cjt3007** [comment]
It works fine for me on iPhone 6 running 8.1.2

**Comment by SimonWaldherr** [comment]
@cjt3007 thanks for this information :+1:

**Comment by AdrianGomezSuarez** [comment]
Hello!

I'm trying to scan the QR code with an iPhone 5s in ur website http://simonwaldherr.github.io/passkit.php/ and when I try to download a Passbook said "Unable to download".

Does it works with lastest iOS versions?

Thanks!

**Comment by cjt3007** [comment]
@AdrianGomezSuarez the code shown is not an "Add to Passbook" code, so if you are trying to scan the QR code with the Passbook app it won't work.

**Comment by AdrianGomezSuarez** [comment]
I mean, when I scan the QR code and it redirects me to the website, I try to download the passbook and show that the passbook is unable to download.

**Comment by cjt3007** [comment]
@AdrianGomezSuarez oh, I see... is it opening the website in Safari, or is it opening it within the QR code app? Because I think UIWebView (the embedded version of Safari in an app) has issues downloading Passes - which is also why home screen webapps have to open the pass download in safari.

**Comment by AdrianGomezSuarez** [comment]
@cjt3007 I have tried by opening Safari, doesn't work =(

**Comment by yasirgit62** [comment]
I have used the library to create the pass. I have created the .pkpass file successfully. when i open the .pkpass file in my android mobile it ask me to open .pkpass file with which application so i choose the pass2u android wallet app to open the pass and it create the pass successfully. But my question is that when we create the pass in the different pass creator websites they will give a qr code that we scan with the mobile wallet app and pass will install in the app . how to do this that i give the qe code so that users can scan from their mobileapplication.

And the second thing is that how to update the pass so that automatically in installed passes in different users mobiles will update and how to count the no of pass install and uninstalls

I am in very trouble . Please solve my problem
